[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oorandom = "11.1.3"
ggez = "0.9.3"
getrandom = "0.2.12"
mp3-duration = "0.1.10"
